import { createHash } from "node:crypto";
import fs from "node:fs";
import readline from "node:readline";
import path from "node:path";
import {
  analyzeRepository,
  buildAgentInputPayload,
  loadState,
  measurementModeForState,
  recordActualWork,
  recordDecisionFatigueEvent,
  recordGuardDecision,
  recordModelUsage,
  saveState,
  shouldRecordAutomaticMeasurement
} from "../analyzer.js";
import { approveDecisionBundle, evaluateAgentAction } from "../core/guard.js";
import {
  appendResearchCalibrationRecord,
  buildResearchCalibrationRecord,
  readResearchCalibrationLedger,
  summarizeResearchCalibrationLedger
} from "../core/research-calibration.js";
import { buildAdaptiveContext, shouldReturnFullContext } from "../core/adaptive-context.js";
import { countTokensForTexts } from "../core/tokenizer.js";
import { buildTaskIntent, deriveWorkIntent, normalizeRequestKey as normalizeIntentKey, requestHash } from "../core/work-intent.js";
import { detectAgentVisibleUsage, summarizeAgentVisibleUsage } from "./codex-usage-detector.js";

const SERVER_NAME = "scopelease";
const SERVER_VERSION = "0.1.0";
const DEFAULT_PROTOCOL_VERSION = "2024-11-05";
const PAIR_RECENCY_WINDOW_MS = 60 * 60 * 1000;

export function startMcpServer({ repoPath = "." } = {}) {
  const defaultRepo = path.resolve(repoPath);
  const rl = readline.createInterface({
    input: process.stdin,
    crlfDelay: Infinity
  });

  let queue = Promise.resolve();
  rl.on("line", (line) => {
    queue = queue
      .then(() => processMcpLine(line, { defaultRepo }))
      .catch((error) => {
        writeMessage(errorResponse(null, -32603, error.message || String(error)));
      });
  });
}

async function processMcpLine(line, { defaultRepo }) {
  const text = String(line || "").trim();
  if (!text) return;
  let message;
  try {
    message = JSON.parse(text);
  } catch (error) {
    writeMessage(errorResponse(null, -32700, `Parse error: ${error.message}`));
    return;
  }

  try {
    const response = await handleMcpMessage(message, { defaultRepo });
    if (response) writeMessage(response);
  } catch (error) {
    if (message.id !== undefined) {
      writeMessage(errorResponse(message.id, -32603, error.message || String(error)));
    }
  }
}

async function handleMcpMessage(message, { defaultRepo }) {
  const { id, method, params = {} } = message;
  if (!method) return id === undefined ? null : errorResponse(id, -32600, "Invalid request");

  if (method === "initialize") {
    return successResponse(id, {
      protocolVersion: params.protocolVersion || DEFAULT_PROTOCOL_VERSION,
      capabilities: {
        tools: {},
        resources: {}
      },
      serverInfo: {
        name: SERVER_NAME,
        version: SERVER_VERSION
      }
    });
  }

  if (method === "notifications/initialized" || id === undefined) return null;
  if (method === "ping") return successResponse(id, {});
  if (method === "tools/list") return successResponse(id, { tools: mcpTools() });

  if (method === "tools/call") {
    const name = String(params.name || "");
    const args = params.arguments && typeof params.arguments === "object" ? params.arguments : {};
    const result = await callTool(name, args, { defaultRepo });
    return successResponse(id, result);
  }

  if (method === "resources/list") {
    return successResponse(id, {
      resources: [
        {
          uri: `scopelease://state`,
          name: "ScopeLease state",
          description: "Latest ScopeLease state for the configured repository.",
          mimeType: "application/json"
        },
        {
          uri: `scopelease://context-pack`,
          name: "ScopeLease context pack",
          description: "Latest compact context pack generated by ScopeLease.",
          mimeType: "application/json"
        }
      ]
    });
  }

  if (method === "resources/read") {
    const state = loadState(defaultRepo) || {};
    const uri = String(params.uri || "");
    if (uri === "scopelease://state") return successResponse(id, resourceText(uri, state));
    if (uri === "scopelease://context-pack") return successResponse(id, resourceText(uri, state.latestAnalysis?.contextPack || {}));
    return errorResponse(id, -32602, `Unknown resource: ${uri}`);
  }

  return errorResponse(id, -32601, `Method not found: ${method}`);
}

async function callTool(name, args, { defaultRepo }) {
  if (name === "scopelease_get_context") return toolGetContext(args, defaultRepo);
  if (name === "scopelease_explain_delta") return toolExplainDelta(args, defaultRepo);
  if (name === "scopelease_measure") return toolMeasure(args, defaultRepo);
  if (name === "scopelease_record_usage") return toolRecordUsage(args, defaultRepo);
  if (name === "scopelease_detect_agent_usage" || name === "scopelease_detect_codex_usage") return toolDetectAgentUsage(args, defaultRepo);
  if (name === "scopelease_research_calibration") return toolResearchCalibration(args, defaultRepo);
  if (name === "scopelease_guard") return toolGuard(args, defaultRepo);
  if (name === "scopelease_approve") return toolApprove(args, defaultRepo);
  if (name === "scopelease_record_fatigue") return toolRecordFatigue(args, defaultRepo);
  throw new Error(`Unknown tool: ${name}`);
}

function toolGetContext(args, defaultRepo) {
  const repo = resolveRepo(args.repo, defaultRepo);
  const currentRequest = loadCurrentRequestState(repo);
  const envWorkIntent = normalizeText(process.env.SCOPELEASE_WORK_INTENT || "");
  const envPairId = normalizePairId(process.env.SCOPELEASE_PAIR_ID || "");
  const envRunId = normalizeRunId(process.env.SCOPELEASE_RUN_ID || "");
  const explicitRequest = explicitRequestArg(args);
  const hasExplicitRequest = Boolean(explicitRequest);
  const userRequest = normalizeText(explicitRequest || currentRequest.userRequest);
  const currentMatches = normalizeRequestKey(currentRequest.userRequest || "") === normalizeRequestKey(userRequest);
  const explicitRunOrPair = Boolean(args.runId || args.run_id || args.pairId || args.pair_id || args.pair);
  const explicitIntent = Boolean(args.workIntent || args.work_intent || args.intent);
  const useCurrentScope = Boolean(
    currentRequest.userRequest &&
    currentRequest.runId &&
    currentRequest.pairId &&
    !explicitRunOrPair &&
    !explicitIntent &&
    (!hasExplicitRequest || looksLikeCurrentScopeRequest(explicitRequest))
  );
  const effectiveRequest = useCurrentScope ? currentRequest.userRequest || userRequest : userRequest;
  const workIntent = normalizeWorkIntent({
    ...args,
    workIntent: args.workIntent || args.work_intent || args.intent || (useCurrentScope ? "" : envWorkIntent)
  }, effectiveRequest, currentRequest, { forceCurrent: useCurrentScope });
  const runId = normalizeRunId(
    args.runId || args.run_id || ((currentMatches || useCurrentScope) ? currentRequest.runId : "") || envRunId
  );
  const pairId = normalizePairId(
    args.pairId || args.pair_id || args.pair || ((currentMatches || useCurrentScope) ? currentRequest.pairId : "") || envPairId
  );
  const budget = Number(args.budget || 8000);
  const format = ["prompt", "summary", "payload"].includes(args.format) ? args.format : "payload";
  const contextMode = args.mode || args.contextMode || args.context_mode || "auto";
  const analysis = analyzeRepository(repo, analysisOptionsFromMcpArgs(args, { budget, userRequest: effectiveRequest }));
  const payload = buildAgentInputPayload(analysis.contextPack, { userRequest: effectiveRequest });
  const adaptiveContext = buildAdaptiveContext({
    repoPath: repo,
    request: effectiveRequest,
    analysis,
    payload,
    mode: contextMode
  });
  const contextText = shouldReturnFullContext(adaptiveContext)
    ? payload.codexInput?.text || JSON.stringify(payload.structuredContext?.input || {})
    : adaptiveContext.text;
  const taskIntent = buildTaskIntent({ request: effectiveRequest, workIntent }, {
    pairId,
    paths: (payload.readPlan || []).map((item) => item.path || item.id || item.label).filter(Boolean),
    decisionNeeded: payload.decisionGate?.canAutoApplyPatch === false
  });
  const measurementState = loadState(repo) || {};
  const measurementMode = measurementModeForState(measurementState);
  const shouldRecordContext = args.record !== false && shouldRecordAutomaticMeasurement(measurementState, "mcp:scopelease_get_context");
  const promotion = shouldRecordContext
    ? promoteCurrentRunToScopeLease(repo, { currentRequest, workIntent, pairId, runId })
    : { promoted: false, reason: "measurement_mode_off" };
  const event = shouldRecordContext ? recordMcpContextEvent(repo, {
    tool: "scopelease_get_context",
    userRequest: payload.userRequest?.text || analysis.contextPack?.userRequest?.text || userRequest,
    text: contextText,
    baselineTokens: 0,
    meta: {
      budget,
      format,
      mode: contextMode,
      adaptiveContext: {
        mode: adaptiveContext.mode,
        requestedMode: adaptiveContext.requestedMode,
        tokens: adaptiveContext.tokens,
        chars: adaptiveContext.chars,
        decision: adaptiveContext.decision
      },
      workIntent,
      taskIntent,
      requestHash: useCurrentScope ? (currentRequest.requestHash || requestHash(effectiveRequest)) : requestHash(effectiveRequest),
      runId,
      pairId,
      promotion,
      repoScopeTokens: analysis.contextPack?.tokenEconomy?.fullRepoTokens || 0,
      contextField: payload.structuredContext?.field || "contextPack.agentContext",
      codexInputField: shouldReturnFullContext(adaptiveContext) ? payload.field || "codexInput.text" : "adaptiveContext.text"
    }
  }) : null;
  const summary = summarizeContextPayload(analysis, payload, event, { pairId, taskIntent, adaptiveContext });
  summary.measurementMode = measurementMode;
  summary.recorded = Boolean(event);

  if (format === "prompt") {
    return toolResult(contextText || "", summary);
  }

  if (format === "summary") {
    return toolResult(JSON.stringify(summary, null, 2), summary);
  }

  return toolResult(JSON.stringify({
    ...summary,
    codexInput: payload.codexInput,
    structuredContext: payload.structuredContext,
    decisionGate: payload.decisionGate,
    usefulness: payload.usefulness,
    readPlan: payload.readPlan,
    avoidPlan: payload.avoidPlan,
    traceLedger: payload.traceLedger
  }, null, 2), summary);
}

function toolExplainDelta(args, defaultRepo) {
  const repo = resolveRepo(args.repo, defaultRepo);
  const result = stripInternalFields(buildDeltaResult(args, repo));
  return toolResult(JSON.stringify(result, null, 2), result);
}

function buildDeltaResult(args, repo) {
  const state = loadState(repo) || {};
  const currentRequest = loadCurrentRequestState(repo);
  const explicitRequest = explicitRequestArg(args);
  const useCurrentRequest = Boolean(!explicitRequest || looksLikeContinuationRequest(explicitRequest));
  const requestedText = normalizeText(useCurrentRequest ? (explicitRequest || currentRequest.userRequest) : explicitRequest);
  const latestAnalysis = state.latestAnalysis || null;
  const latestRequest = normalizeText(latestAnalysis?.contextPack?.userRequest?.text || latestAnalysis?.userRequest || "");
  const graphOptions = graphBackendOptionsFromMcpArgs(args);
  const canUseLatestAnalysis = !Object.keys(graphOptions).length &&
    latestAnalysis &&
    normalizeRequestKey(latestRequest) === normalizeRequestKey(requestedText);
  const analysis = canUseLatestAnalysis
    ? latestAnalysis
    : analyzeRepository(repo, analysisOptionsFromMcpArgs(args, { userRequest: requestedText }));
  const userRequest = normalizeText(requestedText || analysis.contextPack?.userRequest?.text || analysis.userRequest);
  const workIntent = normalizeWorkIntent(args, userRequest, currentRequest);
  const currentMatches = normalizeRequestKey(currentRequest.userRequest || "") === normalizeRequestKey(userRequest);
  const runId = normalizeRunId(args.runId || args.run_id || (currentMatches ? currentRequest.runId : ""));
  const pairId = normalizePairId(args.pairId || args.pair_id || args.pair || (currentMatches ? currentRequest.pairId : ""));
  const requestKey = normalizeRequestKey(userRequest);
  const actualEvents = filterEventsForPairScope(
    filterEventsForWorkIntent(state.actualWorkEvents || [], { workIntent, requestKey }),
    { pairId, runId }
  ).filter((event) => !isControlledProtocolEvent(event));
  const contextEvents = filterEventsForPairScope(
    filterEventsForWorkIntent(state.mcpContextEvents || [], { workIntent, requestKey }),
    { pairId, runId }
  ).filter((event) => !isControlledProtocolEvent(event));
  const economy = analysis.contextPack?.tokenEconomy || {};
  const observedWorkTokens = actualEvents.reduce((sum, event) => sum + Number(event.tokens || 0), 0);
  const providedContextTokens = contextEvents.reduce((sum, event) => sum + Number(event.tokens || 0), 0);
  const latestContextEvent = contextEvents[0] || null;
  const inputCandidateTokens = economy.actualInputTokens || latestContextEvent?.tokens || 0;
  const fullRepoTokens = economy.fullRepoTokens || latestContextEvent?.meta?.repoScopeTokens || 0;
  const observedLowerBoundTokens = providedContextTokens + observedWorkTokens;
  const candidateLowerBoundTokens = (inputCandidateTokens || providedContextTokens) + observedWorkTokens;
  const pairedSavings = buildObservedPairSavings({ workIntent, pairId, runId, actualEvents, contextEvents });
  const researchCalibration = buildResearchCalibrationReport({
    repo,
    userRequest,
    workIntent,
    pairId,
    runId,
    pair: pairedSavings
  });
  const agentVisibleDetection = detectAgentVisibleUsage({ repoPath: repo, state });
  const agentVisibleUsage = summarizeAgentVisibleUsage(agentVisibleDetection);
  agentVisibleUsage.pairedLaneStatus = pairedSavings.status;
  agentVisibleUsage.canMeasureAgentVisiblePairDelta = researchCalibration.claimPolicy?.canClaimExactDelta === true;
  agentVisibleUsage.canClaimAgentVisiblePairSavings = researchCalibration.claimPolicy?.canClaimExactSavings === true;
  agentVisibleUsage.canMeasureAgentVisiblePairSavings = researchCalibration.claimPolicy?.canClaimExactSavings === true;
  const result = {
    kind: "scopelease.mcp_delta",
    repo,
    userRequest,
    measurement: {
      boundary: "agent_visible_context_not_provider_billing",
      scopeleaseProvidedContextTokens: providedContextTokens,
      scopeleaseInputCandidateTokens: inputCandidateTokens,
      observedWorkPayloadTokens: observedWorkTokens,
      observedLowerBoundTokens,
      candidateLowerBoundTokens,
      agentVisibleMeasured: Boolean(providedContextTokens || observedWorkTokens),
      providerUsageExcluded: true
    },
    observedPairSavings: pairedSavings,
    researchCalibration,
    agentVisibleUsage,
    contextCandidate: {
      repoScopeTokens: fullRepoTokens,
      inputCandidateTokens,
      label: "ScopeLease input candidate size and repository scope size; not a savings percentage"
    },
    events: {
      mcpContextEvents: contextEvents.length,
      actualWorkEvents: actualEvents.length,
      providerUsageEventsExcluded: (state.modelUsageEvents || []).length
    },
    caveat: "Pair delta is valid only for a paired work intent: observed default-codex input n versus observed scopelease-codex input m. Positive savings additionally require n > m. Provider/API billing usage and full repository size are excluded from this metric."
  };
  result._internal = {
    latestContextEvent,
    analysis,
    state,
    currentRequest
  };
  return result;
}

function stripInternalFields(value = {}) {
  const { _internal, ...publicValue } = value;
  return publicValue;
}

function toolMeasure(args, defaultRepo) {
  const repo = resolveRepo(args.repo, defaultRepo);
  const currentRequest = loadCurrentRequestState(repo);
  const request = args.request || args.userRequest || currentRequest.userRequest || "";
  const currentMatches = normalizeRequestKey(currentRequest.userRequest || "") === normalizeRequestKey(request);
  const result = recordActualWork(repo, {
    phase: args.phase,
    text: args.text || "",
    source: args.source || "mcp:scopelease_measure",
    label: args.label || args.path || args.phase || "MCP measurement",
    path: args.path || "",
    request,
    workIntent: args.workIntent || args.work_intent || args.intent || (currentMatches ? currentRequest.workIntent : ""),
    lane: args.lane || args.runLane || args.mode || args.source || "",
    pairId: args.pairId || args.pair_id || args.pair || (currentMatches ? currentRequest.pairId : ""),
    runId: args.runId || args.run_id || (currentMatches ? currentRequest.runId : ""),
    baselineTokens: Number(args.baselineTokens || 0)
  });
  return toolResult(JSON.stringify({ ok: true, event: result.event }, null, 2), { ok: true, event: result.event });
}

function toolRecordUsage(args, defaultRepo) {
  const repo = resolveRepo(args.repo, defaultRepo);
  const result = recordModelUsage(repo, {
    ...args,
    source: args.source || "mcp:scopelease_record_usage",
    request: args.request || args.userRequest || ""
  });
  return toolResult(JSON.stringify({ ok: true, event: result.event }, null, 2), { ok: true, event: result.event });
}

function toolDetectAgentUsage(args, defaultRepo) {
  const repo = resolveRepo(args.repo, defaultRepo);
  const state = loadState(repo) || {};
  const result = detectAgentVisibleUsage({
    repoPath: repo,
    state,
    codexHome: args.codexHome || args.codex_home || ""
  });
  return toolResult(JSON.stringify(result, null, 2), result);
}

function toolResearchCalibration(args, defaultRepo) {
  const repo = resolveRepo(args.repo, defaultRepo);
  const delta = buildDeltaResult(args, repo);
  const latestContextEvent = delta._internal.latestContextEvent;
  const taskIntent = latestContextEvent?.taskIntent || buildTaskIntent({
    request: delta.userRequest,
    workIntent: delta.observedPairSavings?.workIntent || delta.researchCalibration?.unit?.workIntent || ""
  }, {
    pairId: delta.observedPairSavings?.pairId || delta.researchCalibration?.unit?.pairId || ""
  });
  const record = buildResearchCalibrationRecord({
    repo,
    request: delta.userRequest,
    taskIntent,
    observedPairSavings: delta.observedPairSavings,
    researchCalibration: delta.researchCalibration,
    agentVisibleUsage: delta.agentVisibleUsage,
    source: args.source || "mcp:scopelease_research_calibration",
    experimentId: args.experimentId || args.experiment_id || "",
    notes: args.notes || ""
  });
  const shouldRecord = args.record !== false;
  const ledger = shouldRecord ? appendResearchCalibrationRecord(repo, record) : null;
  const records = readResearchCalibrationLedger(repo, { limit: Number(args.limit || 50) });
  const result = {
    kind: "scopelease.research_calibration_result",
    scope: "paper_research_only",
    productRuntimeImpact: record.productRuntimeImpact,
    recorded: shouldRecord,
    ledgerPath: ledger?.ledgerPath || null,
    record,
    ledgerSummary: summarizeResearchCalibrationLedger(records),
    caveat: "This is paper/research evidence only. It records observed paired agent-visible inputs and does not change product runtime behavior or run an extra agent."
  };
  return toolResult(JSON.stringify(result, null, 2), result);
}

function toolGuard(args, defaultRepo) {
  const repo = resolveRepo(args.repo, defaultRepo);
  const request = normalizeText(args.request || args.userRequest);
  const analysis = analyzeRepository(repo, analysisOptionsFromMcpArgs(args, { userRequest: request }));
  const state = loadState(repo) || {};
  const verdict = evaluateAgentAction({ action: args.action || {}, analysis, state });
  const recorded = recordGuardDecision(repo, {
    verdict,
    action: args.action || {},
    request,
    source: "mcp:scopelease_guard",
    workIntent: args.workIntent || args.work_intent || args.intent || "",
    pairId: args.pairId || args.pair_id || args.pair || "",
    runId: args.runId || args.run_id || ""
  });
  verdict.eventId = recorded.event.id;
  return toolResult(JSON.stringify(verdict, null, 2), verdict);
}

function toolApprove(args, defaultRepo) {
  const repo = resolveRepo(args.repo, defaultRepo);
  const action = args.action || {};
  const choiceId = normalizeText(args.choiceId || args.choice) || "allow_scoped_patch";
  const analysis = analyzeRepository(repo, analysisOptionsFromMcpArgs(args, {
    userRequest: normalizeText(args.request || args.userRequest)
  }));
  const state = loadState(repo) || {};
  const guardVerdict = evaluateAgentAction({ action, analysis, state });
  if (guardVerdict.verdict !== "ask_once" || !guardVerdict.decisionBundle) {
    throw new Error("No current guard decision requires approval for this action.");
  }
  const decisionBundle = guardVerdict.decisionBundle;
  const lease = approveDecisionBundle({
    analysis,
    state,
    decisionBundle,
    choiceId,
    grantedBy: normalizeText(args.grantedBy) || "human"
  });
  const next = {
    ...state,
    approvalLeases: compactApprovalLeases([lease, ...(state.approvalLeases || [])])
  };
  saveState(repo, next);
  const fatigue = recordDecisionFatigueEvent(repo, {
    type: "approval_lease_created",
    request: normalizeText(args.request || args.userRequest),
    source: "mcp:scopelease_approve",
    actor: normalizeText(args.grantedBy) || "human",
    lease,
    decisionBundleId: decisionBundle.id,
    verdict: guardVerdict.verdict,
    actionGrant: guardVerdict.actionGrant,
    action
  });
  const result = {
    ok: true,
    lease,
    fatigueEvent: fatigue.event,
    previousVerdict: guardVerdict,
    note: "Approval lease recorded. Re-run scopelease_guard for the same request/action before applying."
  };
  return toolResult(JSON.stringify(result, null, 2), result);
}

function toolRecordFatigue(args, defaultRepo) {
  const repo = resolveRepo(args.repo, defaultRepo);
  const result = recordDecisionFatigueEvent(repo, {
    ...args,
    source: args.source || "mcp:scopelease_record_fatigue",
    type: args.type || args.eventType,
    request: args.request || args.userRequest || ""
  });
  return toolResult(JSON.stringify({ ok: true, event: result.event }, null, 2), { ok: true, event: result.event });
}

function recordMcpContextEvent(repo, { tool, userRequest, text, baselineTokens = 0, meta = {} }) {
  const root = path.resolve(repo);
  const state = loadState(root) || {};
  const tokenResult = countTokensForTexts([text], {
    encoding: state.latestAnalysis?.contextPack?.tokenEconomy?.tokenizer?.encoding || state.latestAnalysis?.repoStats?.tokenizer?.encoding
  });
  const tokens = tokenResult.counts[0] || 0;
  const workIntent = deriveWorkIntent({ request: userRequest, workIntent: meta.workIntent || "" });
  const event = {
    kind: "scopelease.mcp_context_event",
    id: `mcp_context_${hashText(JSON.stringify({
      timestamp: Date.now(),
      tool,
      userRequest,
      textHash: hashText(text),
      tokens,
      baselineTokens
    }))}`,
    timestamp: new Date().toISOString(),
    userRequest,
    requestKey: normalizeRequestKey(userRequest),
    requestHash: meta.requestHash || requestHash(userRequest),
    workIntent,
    pairingKey: workIntent,
    taskIntent: meta.taskIntent || buildTaskIntent({ request: userRequest, workIntent }, {
      pairId: meta.pairId || meta.pair_id || "",
      paths: meta.readPlanPaths || []
    }),
    lane: "scopelease-codex",
    pairId: normalizePairId(meta.pairId || meta.pair_id || ""),
    runId: String(meta.runId || "").trim(),
    tool,
    source: "mcp",
    tokens,
    chars: text.length,
    baselineTokens,
    savedTokens: null,
    savedPercent: null,
    tokenCounter: tokenResult.tokenizer?.exact
      ? `${tokenResult.tokenizer.method || "tiktoken"}:${tokenResult.tokenizer.encoding || ""}`
      : "fallback",
    meta,
    note: "ScopeLease MCP가 Codex에 실제 제공한 scopelease-codex lane context payload입니다. 절감률은 같은 workIntent의 default-codex lane 입력과 pair로 비교합니다."
  };
  saveState(root, {
    ...state,
    mcpContextEvents: compactMcpContextEvents([event, ...(state.mcpContextEvents || [])])
  });
  return event;
}

function summarizeContextPayload(analysis, payload, event, fallback = {}) {
  const economy = analysis.contextPack?.tokenEconomy || {};
  const fullRepoTokens = economy.fullRepoTokens || event?.meta?.repoScopeTokens || 0;
  const adaptiveContext = event?.meta?.adaptiveContext
    ? event.meta.adaptiveContext
    : fallback.adaptiveContext || null;
  const inputTokens = event?.tokens || adaptiveContext?.tokens || economy.actualInputTokens || payload.codexInput?.tokens || 0;
  const inputChars = event?.chars || adaptiveContext?.chars || payload.codexInput?.chars || 0;
  return {
    kind: "scopelease.mcp_context_result",
    repo: analysis.repo,
    generatedAt: analysis.generatedAt,
    userRequest: payload.userRequest?.text || analysis.contextPack?.userRequest?.text || analysis.userRequest || "",
    providedContext: {
      field: adaptiveContext && adaptiveContext.mode !== "full_context" ? "adaptiveContext.text" : payload.field || "codexInput.text",
      tokens: inputTokens,
      chars: inputChars,
      eventId: event?.id || null
    },
    adaptiveContext,
    workIntent: event?.workIntent || event?.meta?.workIntent || fallback.workIntent || "",
    pairId: event?.pairId || event?.meta?.pairId || fallback.pairId || "",
    runId: event?.runId || event?.meta?.runId || fallback.runId || "",
    taskIntent: event?.taskIntent || event?.meta?.taskIntent || fallback.taskIntent || null,
    contextCandidate: {
      repoScopeTokens: fullRepoTokens,
      inputCandidateTokens: inputTokens,
      basis: "ScopeLease-provided MCP context size; savings require paired default-codex input n"
    },
    decisionGate: payload.decisionGate || null,
    warning: "This is exact for ScopeLease-provided context. It is not a savings rate until paired with observed default-codex input."
  };
}

function buildObservedPairSavings({ workIntent = "", pairId = "", runId = "", actualEvents = [], contextEvents = [] }) {
  const selected = selectObservedPairRun({ pairId, runId, actualEvents, contextEvents });
  const defaultTokens = selected.defaultTokens;
  const scopeleaseTokens = selected.scopeleaseTokens;
  const measured = selected.measured === true;
  const savedTokens = measured ? defaultTokens - scopeleaseTokens : null;
  const savedPercent = measured ? Math.round((savedTokens / defaultTokens) * 100) : null;
  const deltaDirection = measured ? observedDeltaDirection(savedTokens) : "unknown";
  return {
    kind: "observed_work_intent_pair",
    workIntent,
    pairId: selected.pairId || null,
    runId: selected.runId || null,
    pairSelection: selected.selection,
    formula: "(defaultCodexInputTokens - scopeleaseCodexInputTokens) / defaultCodexInputTokens",
    status: measured ? "measured" : "needs_pair",
    defaultCodexInputTokens: defaultTokens || null,
    scopeleaseCodexInputTokens: scopeleaseTokens || null,
    savedTokens,
    savedPercent,
    deltaDirection,
    canClaimPositiveSavings: measured && savedTokens > 0,
    scopeleaseMcpContextTokens: selected.scopeleaseContextTokens || 0,
    embeddedScopeLeaseContextObserved: Boolean(selected.embeddedScopeLeaseContextObserved),
    embeddedScopeLeaseContextTokens: selected.embeddedScopeLeaseContextTokens || 0,
    eventCounts: selected.eventCounts,
    missing: measured ? [] : [
      defaultTokens ? "" : "default-codex lane measurement",
      scopeleaseTokens ? "" : "scopelease-codex lane measurement"
    ].filter(Boolean)
  };
}

function buildResearchCalibrationReport({
  repo = "",
  userRequest = "",
  workIntent = "",
  pairId = "",
  runId = "",
  pair = {}
} = {}) {
  const defaultReady = Number(pair.defaultCodexInputTokens || 0) > 0;
  const scopeleaseReady = Number(pair.scopeleaseCodexInputTokens || 0) > 0;
  const scopeleaseContextReady = Number(pair.eventCounts?.scopeleaseContext || 0) > 0;
  const pairedLanesReady = defaultReady && scopeleaseReady;
  const exactDeltaReady = pairedLanesReady && scopeleaseContextReady;
  const positiveSavings = exactDeltaReady && Number(pair.savedTokens || 0) > 0;
  const missing = [
    defaultReady ? "" : "default-codex baseline run",
    scopeleaseReady ? "" : "scopelease-codex observed run",
    scopeleaseContextReady ? "" : "scopelease_get_context or embedded ScopeLease context prompt evidence"
  ].filter(Boolean);
  return {
    kind: "scopelease.research_calibration_evidence",
    scope: "separate_from_product_runtime",
    status: exactDeltaReady ? (positiveSavings ? "claim_ready" : "delta_ready_no_savings") : "insufficient_pair",
    productRuntimeImpact: {
      extraAgentRuns: 0,
      note: "ScopeLease 제품의 일반 실행은 두 번째 agent run을 자동으로 만들지 않습니다."
    },
    pairedCalibrationCost: {
      requiresSecondObservedRunWhenMissing: missing.length > 0,
      missingEvidence: missing,
      note: "논문용 exact A/B 검증을 새로 만들면 같은 work intent를 default-codex와 scopelease-codex로 각각 관측해야 하므로, 누락된 lane만큼 추가 실행 비용이 듭니다."
    },
    unit: {
      repo,
      workIntent: workIntent || null,
      pairId: pair.pairId || pairId || null,
      runId: pair.runId || runId || null,
      requestHash: requestHash(userRequest)
    },
    estimator: {
      formula: pair.formula,
      defaultCodexInputTokens: pair.defaultCodexInputTokens,
      scopeleaseCodexInputTokens: pair.scopeleaseCodexInputTokens,
      savedTokens: pair.savedTokens,
      savedPercent: pair.savedPercent
    },
    validityChecks: [
      { check: "same_repo_path", pass: Boolean(repo), evidence: repo || null },
      { check: "same_work_intent", pass: Boolean(workIntent), evidence: workIntent || null },
      { check: "paired_lanes_present", pass: pairedLanesReady, evidence: pair.eventCounts || {} },
      { check: "default_baseline_present", pass: defaultReady, evidence: pair.defaultCodexInputTokens || null },
      { check: "scopelease_context_present", pass: scopeleaseContextReady, evidence: pair.eventCounts?.scopeleaseContext || 0 },
      { check: "positive_savings_observed", pass: positiveSavings, evidence: pair.savedTokens },
      { check: "input_phase_only", pass: true, evidence: "output and scopelease-internal events are excluded before pairing" },
      { check: "provider_usage_excluded", pass: true, evidence: "agent-visible context boundary" }
    ],
    claimPolicy: {
      canClaimExactDelta: exactDeltaReady,
      canClaimExactSavings: positiveSavings,
      canClaimPositiveSavings: positiveSavings,
      deltaDirection: pair.deltaDirection || "unknown",
      allowedClaim: positiveSavings
        ? "paired agent-visible context savings for the same repo path and work intent"
        : exactDeltaReady
          ? "paired agent-visible context delta for the same repo path and work intent; do not call it savings"
          : "positive paired agent-visible context savings only after both lanes, ScopeLease context evidence, and n > m exist",
      rejectedClaims: [
        "full repository size savings",
        "provider/API billing savings",
        "hidden prompt or reasoning token savings",
        "hook trend as exact savings"
      ]
    }
  };
}

function observedDeltaDirection(savedTokens) {
  const value = Number(savedTokens || 0);
  if (value > 0) return "savings";
  if (value < 0) return "increase";
  return "no_change";
}

function selectObservedPairRun({ pairId = "", runId = "", actualEvents = [], contextEvents = [] }) {
  const wantedPairId = normalizePairId(pairId);
  const wantedRunId = normalizeRunId(runId);
  const groups = new Map();
  for (const event of [...(actualEvents || []), ...(contextEvents || [])]) {
    const lane = eventLane(event);
    const contextEvent = event.kind === "scopelease.mcp_context_event" || event.tool === "scopelease_get_context";
    if (contextEvent) {
      if (lane !== "scopelease-codex") continue;
    } else {
      if (!["default-codex", "scopelease-codex"].includes(lane)) continue;
      if (!isObservedInputPayload(event)) continue;
    }
    const eventPairId = eventPairIdValue(event);
    const eventRunId = normalizeRunId(event.runId || event.meta?.runId);
    if (!eventMatchesPairScope({
      eventPairId,
      eventRunId,
      wantedPairId,
      wantedRunId,
      allowDefaultBaselineRun: lane === "default-codex"
    })) continue;
    const key = wantedRunId ? `${eventPairId || "unpaired"}::${wantedRunId}` : eventPairId || eventRunId || "unscoped";
    const group = groups.get(key) || emptyPairGroup({ pairId: eventPairId, runId: eventRunId || "unscoped" });
    group.latestTimestamp = maxIso(group.latestTimestamp, event.timestamp);
    if (eventPairId && !group.pairId) group.pairId = eventPairId;
    if (eventRunId && !group.runId) group.runId = eventRunId;
    if (contextEvent) {
      if (!group.latestContextEvent || compareIso(event.timestamp, group.latestContextEvent.timestamp) >= 0) {
        group.latestContextEvent = event;
      }
      group.eventCounts.scopeleaseContext += 1;
    } else if (lane === "default-codex") group.defaultEvents.push(event);
    else if (lane === "scopelease-codex") {
      group.scopeleaseWorkEvents.push(event);
      if (eventHasEmbeddedScopeLeaseContext(event)) {
        group.embeddedContextEvents.push(event);
        group.eventCounts.scopeleaseContext += 1;
      }
    }
    groups.set(key, group);
  }
  const candidates = [...groups.values()].map((group) => {
    const scopeleaseContextTokens = Number(group.latestContextEvent?.tokens || 0);
    const embeddedScopeLeaseContextTokens = sumEmbeddedScopeLeaseContextTokens(group.embeddedContextEvents);
    const contextTimestamp = group.latestContextEvent?.timestamp || "";
    const contextRunId = normalizeRunId(group.latestContextEvent?.runId || group.latestContextEvent?.meta?.runId);
    const defaultBaselineRunId = contextRunId ? `${contextRunId}:default-baseline` : "";
    const defaultBucket = latestInputBucket(group.defaultEvents, {
      preferredRunId: defaultBaselineRunId,
      anchorTimestamp: contextTimestamp,
      maxDistanceMs: PAIR_RECENCY_WINDOW_MS
    });
    const scopeleaseWorkBucket = latestInputBucket(group.scopeleaseWorkEvents, {
      preferredRunId: contextRunId,
      anchorTimestamp: contextTimestamp,
      maxDistanceMs: PAIR_RECENCY_WINDOW_MS
    });
    const scopeleaseTokens = scopeleaseContextTokens + scopeleaseWorkBucket.tokens;
    const selectedRunId = contextRunId || scopeleaseWorkBucket.runId || defaultBucket.runId || group.runId;
    return {
      pairId: group.pairId || "",
      runId: selectedRunId === "unscoped" ? "" : selectedRunId,
      selection: pairSelectionLabel({ wantedPairId, wantedRunId, group }),
      latestTimestamp: group.latestTimestamp,
      defaultTokens: defaultBucket.tokens,
      scopeleaseTokens,
      scopeleaseContextTokens,
      scopeleaseWorkTokens: scopeleaseWorkBucket.tokens,
      defaultRunId: defaultBucket.runId || null,
      scopeleaseContextRunId: contextRunId || null,
      scopeleaseWorkRunId: scopeleaseWorkBucket.runId || null,
      measured: defaultBucket.tokens > 0 && scopeleaseWorkBucket.tokens > 0 && (scopeleaseContextTokens > 0 || group.embeddedContextEvents.length > 0),
      embeddedScopeLeaseContextObserved: group.embeddedContextEvents.length > 0,
      embeddedScopeLeaseContextTokens,
      eventCounts: {
        default: defaultBucket.count,
        scopeleaseContext: group.eventCounts.scopeleaseContext,
        scopeleaseWork: scopeleaseWorkBucket.count
      }
    };
  });
  candidates.sort((left, right) => {
    if (left.measured !== right.measured) return left.measured ? -1 : 1;
    return compareIso(right.latestTimestamp, left.latestTimestamp);
  });
  return candidates[0] || {
    pairId: wantedPairId,
    runId: wantedRunId,
    selection: pairSelectionLabel({ wantedPairId, wantedRunId }),
    defaultTokens: 0,
    scopeleaseTokens: 0,
    eventCounts: { default: 0, scopeleaseContext: 0, scopeleaseWork: 0 }
  };
}

function eventMatchesPairScope({
  eventPairId = "",
  eventRunId = "",
  wantedPairId = "",
  wantedRunId = "",
  allowDefaultBaselineRun = false
} = {}) {
  if (wantedPairId && eventPairId !== wantedPairId) return false;
  if (!wantedRunId) return true;
  if (!eventRunId) return false;
  return eventRunId === wantedRunId || (allowDefaultBaselineRun && eventRunId === `${wantedRunId}:default-baseline`);
}

function pairSelectionLabel({ wantedPairId = "", wantedRunId = "", group = {} } = {}) {
  if (wantedPairId && wantedRunId) return "explicit_pair_run";
  if (wantedPairId) return "explicit_pair_id";
  if (wantedRunId) return "explicit_run_id";
  if (!group || !Object.keys(group).length) return "none";
  if (group.pairId) return "latest_pair_id";
  return group.runId === "unscoped" ? "latest_unscoped" : "latest_run_id";
}

function emptyPairGroup({ pairId = "", runId = "unscoped" } = {}) {
  return {
    pairId,
    runId,
    latestTimestamp: "",
    defaultEvents: [],
    scopeleaseWorkEvents: [],
    embeddedContextEvents: [],
    latestContextEvent: null,
    eventCounts: { default: 0, scopeleaseContext: 0, scopeleaseWork: 0 }
  };
}

function latestInputBucket(events = [], { preferredRunId = "", anchorTimestamp = "", maxDistanceMs = 0 } = {}) {
  const wantedRunId = normalizeRunId(preferredRunId);
  const byRun = new Map();
  for (const event of events || []) {
    const runId = normalizeRunId(event.runId || event.meta?.runId) || "unscoped";
    const bucket = byRun.get(runId) || { runId, tokens: 0, count: 0, earliestTimestamp: "", latestTimestamp: "" };
    bucket.tokens += Number(event.tokens || 0);
    bucket.count += 1;
    bucket.earliestTimestamp = bucket.earliestTimestamp
      ? (compareIso(event.timestamp, bucket.earliestTimestamp) < 0 ? event.timestamp : bucket.earliestTimestamp)
      : event.timestamp || "";
    bucket.latestTimestamp = maxIso(bucket.latestTimestamp, event.timestamp);
    byRun.set(runId, bucket);
  }
  let buckets = [...byRun.values()];
  if (anchorTimestamp && maxDistanceMs > 0) {
    buckets = buckets.filter((bucket) => bucketWithinWindow(bucket, anchorTimestamp, maxDistanceMs));
  }
  if (wantedRunId && buckets.some((bucket) => bucket.runId === wantedRunId)) {
    return buckets.find((bucket) => bucket.runId === wantedRunId);
  }
  buckets.sort((left, right) => compareIso(right.latestTimestamp, left.latestTimestamp));
  return buckets[0] || { runId: "", tokens: 0, count: 0, earliestTimestamp: "", latestTimestamp: "" };
}

function bucketWithinWindow(bucket = {}, anchorTimestamp = "", maxDistanceMs = 0) {
  const anchorTime = Date.parse(anchorTimestamp || "");
  if (!Number.isFinite(anchorTime) || maxDistanceMs <= 0) return true;
  const times = [bucket.earliestTimestamp, bucket.latestTimestamp]
    .map((timestamp) => Date.parse(timestamp || ""))
    .filter(Number.isFinite);
  if (!times.length) return true;
  return times.some((time) => Math.abs(time - anchorTime) <= maxDistanceMs);
}

function isObservedInputPayload(event = {}) {
  const phase = String(event.phase || event.meta?.phase || "").trim().toLowerCase();
  if (!phase) return true;
  return ["input", "prompt", "user-prompt", "user_prompt", "explore", "edit"].includes(phase);
}

function isControlledProtocolEvent(event = {}) {
  const source = String(event.source || event.meta?.source || "").toLowerCase();
  return source === "pair-harness" || source.startsWith("pair-harness:") || source.startsWith("live-observed-pair-run:");
}

function eventHasEmbeddedScopeLeaseContext(event = {}) {
  return event.scopeleaseContextEmbedded === true || event.meta?.scopeleaseContextEmbedded === true;
}

function sumEmbeddedScopeLeaseContextTokens(events = []) {
  return events.reduce((sum, event) => sum + Number(event.scopeleaseContextTokens || event.meta?.scopeleaseContextTokens || 0), 0);
}

function filterEventsForWorkIntent(events = [], { workIntent = "", requestKey = "" } = {}) {
  const targetIntent = normalizeRequestKey(workIntent);
  const targetRequest = normalizeRequestKey(requestKey);
  return (events || []).filter((event) => {
    const eventIntent = normalizeRequestKey(event.workIntent || event.meta?.workIntent || "");
    const eventRequest = normalizeRequestKey(event.userRequest || event.request || "");
    if (targetIntent) {
      if (eventIntent && (eventIntent === targetIntent || eventIntent === targetRequest)) return true;
      if (eventRequest && eventRequest === targetRequest) return true;
      return deriveWorkIntent({ request: event.userRequest || event.request || event.requestKey || "" }) === targetIntent;
    }
    return eventRequest === targetRequest;
  });
}

function filterEventsForPairScope(events = [], { pairId = "", runId = "" } = {}) {
  const wantedPairId = normalizePairId(pairId);
  const wantedRunId = normalizeRunId(runId);
  if (!wantedPairId && !wantedRunId) return events;
  return (events || []).filter((event) => {
    return eventMatchesPairScope({
      eventPairId: eventPairIdValue(event),
      eventRunId: normalizeRunId(event.runId || event.meta?.runId),
      wantedPairId,
      wantedRunId,
      allowDefaultBaselineRun: eventLane(event) === "default-codex"
    });
  });
}

function eventLane(event = {}) {
  const value = String(event.lane || event.runLane || event.meta?.lane || event.source || "").toLowerCase().replace(/[_\s]+/g, "-");
  if (value === "scopelease-internal" || value.startsWith("watch:auto")) return "scopelease-internal";
  if (/(default|baseline|without-scopelease|no-scopelease|plain-codex)/.test(value)) return "default-codex";
  if (/(scopelease-codex|with-scopelease|mcp|scopelease)/.test(value)) return "scopelease-codex";
  return "";
}

function eventPairIdValue(event = {}) {
  return normalizePairId(event.pairId || event.pair_id || event.meta?.pairId || event.meta?.pair_id);
}

function normalizeWorkIntent(args = {}, fallback = "", currentRequest = {}, options = {}) {
  const fallbackKey = normalizeRequestKey(fallback);
  const currentKey = normalizeRequestKey(currentRequest.userRequest || "");
  const useCurrent = Boolean(currentRequest.workIntent && (options.forceCurrent || !fallbackKey || fallbackKey === currentKey));
  return deriveWorkIntent({
    request: fallback || currentRequest.userRequest || "",
    workIntent: args.workIntent || args.work_intent || args.intent || (useCurrent ? currentRequest.workIntent : "")
  });
}

function promoteCurrentRunToScopeLease(repo, { currentRequest = {}, workIntent = "", pairId = "", runId = "" } = {}) {
  const root = path.resolve(repo || ".");
  const wantedRunId = normalizeRunId(runId);
  if (!wantedRunId) return { promoted: false, updatedEvents: 0, reason: "missing_run_id" };

  const state = loadState(root) || {};
  let updatedEvents = 0;
  const baselineClones = [];
  const effectivePairId = pairId || currentRequest.pairId || "";
  const effectiveWorkIntent = workIntent || currentRequest.workIntent || "";
  const shouldCloneDefaultBaseline = !hasExistingDefaultPairBaseline(state.actualWorkEvents || [], {
    pairId: effectivePairId,
    workIntent: effectiveWorkIntent,
    runId: wantedRunId
  });
  const actualWorkEvents = (state.actualWorkEvents || []).map((event) => {
    if (normalizeRunId(event.runId || event.meta?.runId) !== wantedRunId) return event;
    if (eventLane(event) === "scopelease-internal") return event;
    if (shouldCloneDefaultBaseline && isDefaultInputEvent(event)) {
      baselineClones.push(defaultBaselineClone(event, { workIntent, pairId, runId: wantedRunId }));
    }
    const next = { ...event, lane: "scopelease-codex" };
    if (workIntent) next.workIntent = workIntent;
    if (pairId) next.pairId = pairId;
    if (JSON.stringify(next) !== JSON.stringify(event)) updatedEvents += 1;
    return next;
  });

  if (updatedEvents > 0 || baselineClones.length > 0) {
    saveState(root, {
      ...state,
      actualWorkEvents: compactPromotedActualWorkEvents([...baselineClones, ...actualWorkEvents])
    });
  }

  if (normalizeRunId(currentRequest.runId) === wantedRunId) {
    writeCurrentRequestState(root, {
      ...currentRequest,
      lane: "scopelease-codex",
      workIntent: workIntent || currentRequest.workIntent || "",
      pairingKey: workIntent || currentRequest.workIntent || "",
      taskIntent: currentRequest.taskIntent || buildTaskIntent({
        request: currentRequest.userRequest || "",
        workIntent: workIntent || currentRequest.workIntent || ""
      }, { pairId: pairId || currentRequest.pairId || "" }),
      pairId: pairId || currentRequest.pairId || "",
      scopeleaseContextSeenAt: new Date().toISOString()
    });
  }

  return {
    promoted: true,
    runId: wantedRunId,
    pairId: pairId || "",
    updatedEvents,
    defaultBaselineClones: baselineClones.length
  };
}

function hasExistingDefaultPairBaseline(events = [], { pairId = "", workIntent = "", runId = "" } = {}) {
  const wantedPairId = normalizePairId(pairId);
  const wantedIntent = normalizeRequestKey(workIntent);
  const wantedRunId = normalizeRunId(runId);
  const wantedBaselineRunId = wantedRunId ? `${wantedRunId}:default-baseline` : "";
  if ((!wantedPairId && !wantedIntent) || !wantedBaselineRunId) return false;
  return (events || []).some((event) => {
    if (eventLane(event) !== "default-codex") return false;
    if (event.autoPairBaseline !== true) return false;
    if (normalizeRunId(event.runId || event.meta?.runId) !== wantedBaselineRunId) return false;
    const eventPairId = eventPairIdValue(event);
    const eventIntent = normalizeRequestKey(event.workIntent || event.meta?.workIntent || "");
    if (wantedPairId) return eventPairId === wantedPairId;
    return wantedIntent && eventIntent === wantedIntent;
  });
}

function isDefaultInputEvent(event = {}) {
  if (eventLane(event) !== "default-codex") return false;
  const phase = String(event.phase || event.meta?.phase || "").trim().toLowerCase();
  return !phase || ["input", "prompt", "user-prompt", "user_prompt"].includes(phase);
}

function defaultBaselineClone(event = {}, { workIntent = "", pairId = "", runId = "" } = {}) {
  const clone = {
    ...event,
    id: `${event.id || hashText(JSON.stringify(event))}:default_baseline`,
    lane: "default-codex",
    runId: `${normalizeRunId(runId) || normalizeRunId(event.runId || event.meta?.runId) || "codex"}:default-baseline`,
    source: `${event.source || "codex-hook"}:auto-default-baseline`,
    label: `${event.label || "Codex user prompt"} baseline`,
    autoPairBaseline: true,
    note: "ScopeLease MCP context promoted this Codex run to scopelease-codex; this clone preserves the pre-ScopeLease visible input as the default-codex baseline for paired measurement."
  };
  if (workIntent) clone.workIntent = workIntent;
  if (pairId) clone.pairId = pairId;
  return clone;
}

function compactPromotedActualWorkEvents(events = []) {
  const output = [];
  const seen = new Set();
  for (const event of events || []) {
    if (!event?.id || seen.has(event.id)) continue;
    seen.add(event.id);
    output.push(event);
    if (output.length >= 500) break;
  }
  return output;
}

function writeCurrentRequestState(repo, state = {}) {
  const root = path.resolve(repo || ".");
  try {
    const dir = path.join(root, ".decision");
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "hook-current-request.json"), `${JSON.stringify(state, null, 2)}\n`);
    if (state.userRequest) fs.writeFileSync(path.join(dir, "hook-current-request.txt"), state.userRequest);
  } catch {}
}

function normalizeRunId(value = "") {
  return String(value || "").trim();
}

function normalizePairId(value = "") {
  return String(value || "").trim();
}

function compareIso(left = "", right = "") {
  const leftTime = Date.parse(left || "");
  const rightTime = Date.parse(right || "");
  if (!Number.isFinite(leftTime) && !Number.isFinite(rightTime)) return 0;
  if (!Number.isFinite(leftTime)) return -1;
  if (!Number.isFinite(rightTime)) return 1;
  return leftTime - rightTime;
}

function maxIso(left = "", right = "") {
  return compareIso(left, right) >= 0 ? left : right;
}

function mcpTools() {
  return [
    {
      name: "scopelease_get_context",
      description: "Build compact ScopeLease KG context for a repo and record the exact context payload tokens provided through MCP.",
      inputSchema: {
        type: "object",
        properties: {
          repo: { type: "string", description: "Repository path. Defaults to the repo used to start the MCP server." },
          request: { type: "string", description: "Current user request." },
          workIntent: { type: "string", description: "Stable intent key for pairing default-codex and scopelease-codex observations." },
          pairId: { type: "string", description: "Stable pair id shared by a default-codex baseline run and an scopelease-codex run." },
          runId: { type: "string", description: "Optional run id for this scopelease-codex context event." },
          budget: { type: "number", description: "Context token budget.", default: 8000 },
          mode: { type: "string", enum: ["auto", "observe", "micro", "full"], description: "Adaptive context mode. auto withholds full context when it is not token-efficient.", default: "auto" },
          format: { type: "string", enum: ["payload", "prompt", "summary"], default: "payload" },
          graphBackendName: { type: "string", description: "Optional label for an external CodeGraph-like payload." },
          graphBackendPayload: { type: "object", description: "Optional graph-shaped payload with nodes/edges or vertices/relationships." },
          record: { type: "boolean", description: "Record an scopelease.mcp_context_event.", default: true }
        }
      }
    },
    {
      name: "scopelease_explain_delta",
      description: "Explain paired default-codex versus scopelease-codex observed agent-visible input deltas; only positive deltas are savings.",
      inputSchema: {
        type: "object",
        properties: {
          repo: { type: "string" },
          request: { type: "string" },
          workIntent: { type: "string" },
          pairId: { type: "string" },
          runId: { type: "string" },
          graphBackendName: { type: "string" },
          graphBackendPayload: { type: "object" }
        }
      }
    },
    {
      name: "scopelease_measure",
      description: "Record observed work payload tokens for input, explore, edit, or output phases.",
      inputSchema: {
        type: "object",
        required: ["phase", "text"],
        properties: {
          repo: { type: "string" },
          phase: { type: "string", enum: ["input", "explore", "edit", "output"] },
          text: { type: "string" },
          label: { type: "string" },
          path: { type: "string" },
          request: { type: "string" },
          workIntent: { type: "string" },
          lane: { type: "string", enum: ["default-codex", "scopelease-codex"] },
          pairId: { type: "string" },
          runId: { type: "string" },
          baselineTokens: { type: "number" }
        }
      }
    },
    {
      name: "scopelease_record_usage",
      description: "Record provider/model usage when a caller already has usage token fields. This does not proxy or create API calls.",
      inputSchema: {
        type: "object",
        properties: {
          repo: { type: "string" },
          request: { type: "string" },
          provider: { type: "string" },
          model: { type: "string" },
          inputTokens: { type: "number" },
          outputTokens: { type: "number" },
          reasoningTokens: { type: "number" },
          cachedInputTokens: { type: "number" },
          totalTokens: { type: "number" },
          usage: { type: "object" }
        }
      }
    },
    {
      name: "scopelease_detect_agent_usage",
      description: "Detect local Codex/ScopeLease agent-visible context usage sources without provider/API usage.",
      inputSchema: {
        type: "object",
        properties: {
          repo: { type: "string" },
          codexHome: { type: "string", description: "Optional Codex home override for tests or alternate installs." }
        }
      }
    },
    {
      name: "scopelease_detect_codex_usage",
      description: "Legacy alias for scopelease_detect_agent_usage.",
      inputSchema: {
        type: "object",
        properties: {
          repo: { type: "string" },
          codexHome: { type: "string", description: "Optional Codex home override for tests or alternate installs." }
        }
      }
    },
    {
      name: "scopelease_research_calibration",
      description: "Create a paper/research-only calibration record from observed paired agent-visible evidence. This does not run another agent or affect product runtime.",
      inputSchema: {
        type: "object",
        properties: {
          repo: { type: "string" },
          request: { type: "string" },
          workIntent: { type: "string" },
          pairId: { type: "string" },
          runId: { type: "string" },
          experimentId: { type: "string", description: "Optional stable experiment id for paper calibration." },
          notes: { type: "string" },
          record: { type: "boolean", description: "Append to .decision/research-calibration.jsonl.", default: true },
          limit: { type: "number", description: "Number of recent ledger records to summarize.", default: 50 }
        }
      }
    },
    {
      name: "scopelease_guard",
      description: "Evaluate a proposed agent action against ScopeLease decision gate and approval leases.",
      inputSchema: {
        type: "object",
        required: ["action"],
        properties: {
          repo: { type: "string" },
          request: { type: "string" },
          graphBackendName: { type: "string" },
          graphBackendPayload: { type: "object" },
          action: { type: "object" }
        }
      }
    },
    {
      name: "scopelease_approve",
      description: "Record a human approval lease for a scoped action after the user explicitly approves proceeding.",
      inputSchema: {
        type: "object",
        required: ["action"],
        properties: {
          repo: { type: "string" },
          request: { type: "string" },
          graphBackendName: { type: "string" },
          graphBackendPayload: { type: "object" },
          action: { type: "object" },
          choiceId: {
            type: "string",
            enum: ["allow_scoped_patch", "prepare_only", "allow_low_risk_subset", "allow_task_scoped_network"],
            default: "allow_scoped_patch"
          },
          grantedBy: { type: "string", default: "human" }
        }
      }
    },
    {
      name: "scopelease_record_fatigue",
      description: "Record a decision-fatigue event for human evaluation, such as a prompt shown, lease hit, override, or flow break.",
      inputSchema: {
        type: "object",
        required: ["type"],
        properties: {
          repo: { type: "string" },
          type: {
            type: "string",
            enum: [
              "human_prompt_shown",
              "approval_prompt_shown",
              "human_decision_recorded",
              "approval_lease_hit",
              "approval_lease_miss",
              "approval_lease_created",
              "repeated_question_suppressed",
              "clarification_prompt_shown",
              "override_recorded",
              "flow_break"
            ]
          },
          request: { type: "string" },
          workIntent: { type: "string" },
          pairId: { type: "string" },
          runId: { type: "string" },
          actor: { type: "string", default: "human" },
          leaseId: { type: "string" },
          action: { type: "object" },
          label: { type: "string" },
          durationMs: { type: "number" },
          note: { type: "string" }
        }
      }
    }
  ];
}

function toolResult(text, structuredContent = null) {
  return {
    content: [{ type: "text", text }],
    ...(structuredContent ? { structuredContent } : {})
  };
}

function resourceText(uri, value) {
  return {
    contents: [
      {
        uri,
        mimeType: "application/json",
        text: JSON.stringify(value, null, 2)
      }
    ]
  };
}

function successResponse(id, result) {
  return { jsonrpc: "2.0", id, result };
}

function errorResponse(id, code, message) {
  return {
    jsonrpc: "2.0",
    id,
    error: { code, message }
  };
}

function writeMessage(message) {
  process.stdout.write(`${JSON.stringify(message)}\n`);
}

function resolveRepo(value, defaultRepo) {
  return path.resolve(normalizeText(value) || defaultRepo || ".");
}

function analysisOptionsFromMcpArgs(args = {}, { budget = 8000, userRequest = "" } = {}) {
  return {
    budget: Number(budget || args.budget || 8000),
    userRequest,
    ...graphBackendOptionsFromMcpArgs(args)
  };
}

function graphBackendOptionsFromMcpArgs(args = {}) {
  const payload = args.graphBackendPayload || args.graph_backend_payload || null;
  const name = normalizeText(
    args.graphBackendName ||
    args.graph_backend_name ||
    args.graphBackend ||
    args.graph_backend
  );
  const result = {};
  if (payload && typeof payload === "object" && !Array.isArray(payload)) {
    result.graphBackendPayload = payload;
    result.graphBackendSource = "mcp";
  }
  if (name) result.graphBackendName = name;
  return result;
}

function normalizeText(value) {
  if (value === true || value === false || value == null) return "";
  return String(value || "").trim();
}

function explicitRequestArg(args = {}) {
  if (Object.hasOwn(args, "request")) return normalizeText(args.request);
  if (Object.hasOwn(args, "userRequest")) return normalizeText(args.userRequest);
  if (Object.hasOwn(args, "user_request")) return normalizeText(args.user_request);
  return "";
}

function looksLikeStandaloneRequest(value = "") {
  const text = normalizeText(value);
  if (!text) return false;
  if (/(^|[\s"'`])(?:[A-Za-z0-9_.-]+\/)+[A-Za-z0-9_.-]+\.[A-Za-z0-9]+/.test(text)) return true;
  if (/\b(?:src|test|tests|public|docs|examples)\/[^\s]+/.test(text)) return true;
  if (/\b(?:fix|implement|modify|patch|refactor|test|debug|export|record|evaluate|generate|review|audit|inspect|check|harden|secure)\b/i.test(text) && text.length >= 24) return true;
  if (/[가-힣]/.test(text) && /(수정|구현|고쳐|테스트|평가|기록|내보내|생성|보강|추가|검토|리뷰|확인|점검|보안|제품화)/.test(text) && text.length >= 12) return true;
  return false;
}

function looksLikeContinuationRequest(value = "") {
  const text = normalizeText(value).replace(/\s+/g, " ").toLowerCase();
  if (!text || text.length > 140) return false;
  if (looksLikeStandaloneRequest(text)) return false;
  if (/^(ok|okay|yes|yep|go ahead|proceed|continue|do it)\b/.test(text)) return true;
  if (/^(응|ㅇㅇ|그래|좋아|진행|계속|해봐|고쳐|수정|적용|다 고치자|전부 고쳐|모두 고쳐)/.test(text)) return true;
  return /(고치자|진행해|해봐|적용해|수정해)/.test(text) && /(그|다|전부|모두|그렇게|그럼)/.test(text);
}

function looksLikeCurrentScopeRequest(value = "") {
  const text = normalizeText(value).replace(/\s+/g, " ").toLowerCase();
  if (!text || text.length > 160) return false;
  if (looksLikeContinuationRequest(text)) return true;
  if (looksLikeStandaloneRequest(text)) return false;
  return /\b(?:scopelease|mcp|context|ctx)\b/.test(text) || /(컨텍스트|맥락|문맥|호출)/.test(text);
}

function normalizeRequestKey(value) {
  return normalizeIntentKey(value);
}

function loadCurrentRequestState(repo) {
  const root = path.resolve(repo || ".");
  const jsonPath = path.join(root, ".decision", "hook-current-request.json");
  try {
    const parsed = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {}
  try {
    const userRequest = fs.readFileSync(path.join(root, ".decision", "hook-current-request.txt"), "utf8").trim();
    return userRequest ? {
      userRequest,
      workIntent: deriveWorkIntent({ request: userRequest }),
      pairingKey: deriveWorkIntent({ request: userRequest }),
      taskIntent: buildTaskIntent({ request: userRequest }),
      requestHash: requestHash(userRequest),
      runId: ""
    } : {};
  } catch {
    return {};
  }
}

function compactMcpContextEvents(events = []) {
  const output = [];
  const seen = new Set();
  for (const event of events) {
    if (!event?.id || seen.has(event.id)) continue;
    seen.add(event.id);
    output.push(event);
    if (output.length >= 120) break;
  }
  return output;
}

function compactApprovalLeases(leases = []) {
  const output = [];
  const seen = new Set();
  for (const lease of leases) {
    if (!lease?.id || seen.has(lease.id)) continue;
    seen.add(lease.id);
    output.push(lease);
    if (output.length >= 40) break;
  }
  return output;
}

function hashText(value) {
  return createHash("sha256").update(String(value || "")).digest("hex").slice(0, 16);
}
